alias: Ecobee - Away Input
trigger:
  - platform: state
    entity_id: sensor.ecobee_away
action:
  service_template: >
    {% if is_state('sensor.ecobee_away', 'off') %}
      input_boolean.turn_off
    {% elif is_state('sensor.ecobee_away', 'on') %}
      input_boolean.turn_on
    {% else %}
    {% endif %}
  entity_id: input_boolean.ecobee_away